
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed May 13 08:18:51 ICT 2015
//----------------------------------------------------

package src;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int GREATERTHAN = 24;
  public static final int DIVIDE = 5;
  public static final int XOR = 33;
  public static final int INTEGER = 35;
  public static final int NOTEQUAL = 27;
  public static final int LPAREN = 6;
  public static final int SEMI = 8;
  public static final int INT = 18;
  public static final int MINUS = 3;
  public static final int RPAREN = 7;
  public static final int NOT = 30;
  public static final int AND = 28;
  public static final int EQUALTO = 22;
  public static final int LESSTHAN = 23;
  public static final int OR = 29;
  public static final int BOOL = 20;
  public static final int BEGIN = 16;
  public static final int PLUS = 2;
  public static final int IF = 11;
  public static final int ID = 37;
  public static final int FLOATING = 36;
  public static final int EOF = 0;
  public static final int BOOLEAN = 34;
  public static final int RETURN = 32;
  public static final int error = 1;
  public static final int VOID = 31;
  public static final int EQ = 9;
  public static final int TIMES = 4;
  public static final int ENDIF = 21;
  public static final int ELSE = 13;
  public static final int WHILE = 14;
  public static final int LESSTHANEQ = 25;
  public static final int FLOAT = 19;
  public static final int THEN = 12;
  public static final int END = 17;
  public static final int GREATERTHANEQ = 26;
  public static final int PRINT = 10;
  public static final int DO = 15;
}

